name: Deploy to ECR

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secretds.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{  }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #   # Build a docker container and
      #   # push it to ECR so that it can
      #   # be deployed to ECS.
      #   docker build -t $AWS_ECR_LOGIN_URL/$ECR_REPOSITORY:$IMAGE_TAG .
      #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #   echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.AWS_ECR_LOGIN_URL }}/math_score:latest .

      # - name: Push Docker image to ECR
      #   run: |
      #     docker push ${{ secrets.AWS_ECR_LOGIN_URL }}/math_score:latest
